data:
  train_csv: ".../pretrain/manifest.csv"
  val_csv: ".../val/manifest.csv"
  num_channels: 16
  T: 2000
  batch_size: 512

training:
  epochs: 100
  save_recon_every_n_epochs: 10
  output_dir: "8-mask_100-epochs"

optimizer:
  lr: 1e-4
  betas: [0.9, 0.95]
  weight_decay: 0.05

scheduler:
  name: cosine
  eta_min: 1e-6

model:
  mask_ratio: 0.8
  embed_dim: 128
  transformer_depth: 2
  nhead: 2
  ff_dim: 512
  conv_decoder_hidden: 64
  dropout: 0.0
